Document: canaima-mod-burg
Title: Debian canaima-mod-burg Manual
Author: <insert document author here>
Abstract: This manual describes what canaima-mod-burg is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/canaima-mod-burg/canaima-mod-burg.sgml.gz

Format: postscript
Files: /usr/share/doc/canaima-mod-burg/canaima-mod-burg.ps.gz

Format: text
Files: /usr/share/doc/canaima-mod-burg/canaima-mod-burg.text.gz

Format: HTML
Index: /usr/share/doc/canaima-mod-burg/html/index.html
Files: /usr/share/doc/canaima-mod-burg/html/*.html
